### ISSUE TITLE
Still getting database errors about admin and I can not create a user

### ISSUE THREAD

**Issue by Morethanevil** [sassanix/Warracker#80]
Hi, thanks for Warracker!

I tried the new beta, because it should not need admin privileges anymore. I am using a postgres database from my host, which I created before starting Warracker like this:

```sql
CREATE USER warracker WITH PASSWORD 'strongpassword';
CREATE DATABASE warrackerdb WITH OWNER warracker ENCODING 'utf8' TEMPLATE template0;
```

After starting the container the log looks like this:

[warracker.txt](https://github.com/user-attachments/files/20753807/warracker.txt)

The container starts anyway successfully, but I can not create a user. 

```bash
warracker  | INFO:backend.notifications:Retrying database connection in 2 seconds...
warracker  | WARNING:backend.notifications:Database connection attempt 2 failed: server closed the connection unexpectedly
warracker  |    This probably means the server terminated abnormally
warracker  |    before or while processing the request.
warracker  |
warracker  | INFO:backend.notifications:Retrying database connection in 2 seconds...
warracker  | ERROR:backend.notifications:Error determining notification eligibility: FEHLER:  Spalte up.timezone existiert nicht
warracker  | LINE 2: ....id, u.email, u.first_name, up.notification_time, up.timezon...
warracker  |                                                              ^
warracker  |
warracker  | INFO:apscheduler.executors.default:Job "init_scheduler.<locals>.notification_wrapper (trigger: interval[0:02:00], next run at: 2025-06-16 08:50:13 UTC)" executed successfully
warracker  | ERROR:backend.notifications:Error determining notification eligibility: FEHLER:  Spalte up.timezone existiert nicht
warracker  | LINE 2: ....id, u.email, u.first_name, up.notification_time, up.timezon...
warracker  |                                                              ^
warracker  |
warracker  | INFO:apscheduler.executors.default:Job "init_scheduler.<locals>.notification_wrapper (trigger: interval[0:02:00], next run at: 2025-06-16 08:50:13 UTC)" executed successfully
warracker  | ERROR:backend.notifications:Error determining notification eligibility: FEHLER:  Spalte up.timezone existiert nicht
warracker  | LINE 2: ....id, u.email, u.first_name, up.notification_time, up.timezon...
warracker  |                                                              ^
warracker  |
warracker  | INFO:apscheduler.executors.default:Job "init_scheduler.<locals>.notification_wrapper (trigger: interval[0:02:00], next run at: 2025-06-16 08:50:13 UTC)" executed successfully
warracker  | ERROR:backend.notifications:Error determining notification eligibility: FEHLER:  Spalte up.timezone existiert nicht
warracker  | LINE 2: ....id, u.email, u.first_name, up.notification_time, up.timezon...
warracker  |                                                              ^
warracker  |
warracker  | INFO:apscheduler.executors.default:Job "init_scheduler.<locals>.notification_wrapper (trigger: interval[0:02:00], next run at: 2025-06-16 08:50:13 UTC)" executed successfully
warracker  | ERROR:backend.oidc_handler:[OIDC_HANDLER] Error fetching OIDC status: FEHLER:  Relation »site_settings« existiert nicht
warracker  | LINE 1: SELECT key, value FROM site_settings WHERE key IN ('oidc_ena...
warracker  |                                ^
warracker  |
warracker  | ERROR:app:Registration error: FEHLER:  Spalte »is_owner« von Relation »users« existiert nicht
warracker  | LINE 1: ..., password_hash, first_name, last_name, is_admin, is_owner) ...
warracker  |                                                              ^
warracker  |
```

My compose.yaml:

```yaml
services:
  warracker:
    image: ghcr.io/sassanix/warracker/main:latest
    container_name: warracker
#    ports:
#      - "8005:80"
    networks:
      innendienst:
        ipv4_address: 172.20.0.71
        ipv6_address: fd00:112::71
    volumes:
      - /docker/warracker/uploads:/data/uploads
      - /var/run/postgresql:/var/run/postgresql
    environment:
       DB_HOST: ${DB_HOST}
       DB_NAME: ${DB_NAME}
       DB_USER: ${DB_USER}
       DB_PASSWORD: ${DB_PASSWORD}
       SMTP_HOST: ${SMTP_HOST}
       SMTP_PORT: 465
       SMTP_USERNAME: ${SMTP_USERNAME}
       SMTP_PASSWORD: ${SMTP_PASSWORD}
       SECRET_KEY: ${SECRET_KEY}
       MAX_UPLOAD_MB: 50 # Example: Set max upload size to 32MB
       NGINX_MAX_BODY_SIZE_VALUE: 50M # For Nginx, ensure this matches MAX_UPLOAD_MB in concept (e.g., 32M)

      # OIDC SSO Configuration (User needs to set these based on their OIDC provider)
       OIDC_PROVIDER_NAME: Authentik
       OIDC_CLIENT_ID: ${OIDC_CLIENT_ID} # e.g., your_oidc_client_id_from_provider
       OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET} # e.g., your_oidc_client_secret_from_provider
       OIDC_ISSUER_URL: ${OIDC_ISSUER_URL} # e.g., https://your-oidc-provider.com/auth/realms/your-realm
       OIDC_SCOPE: ${OIDC_SCOPE}

      # URL settings (Important for OIDC redirects and email links)
      # Ensure these point to the public-facing URL of your application

       FRONTEND_URL: ${FRONTEND_URL}
       APP_BASE_URL: ${APP_BASE_URL}

      # Apprise notifications

       APPRISE_ENABLED: true # Enable/disable Apprise notifications
       APPRISE_URLS: ${APPRISE_URLS} # Comma-separated list of notification URLs (e.g., "mailto://user:pass@gmail.com,discord://webhook_id/webhook_token")
       APPRISE_EXPIRATION_DAYS: 30 # Days before expiration to send notifications (comma-separated)
       APPRISE_NOTIFICATION_TIME: 14:00 # Time of day to send notifications (HH:MM format)
       APPRISE_TITLE_PREFIX: Warracker # Prefix for notification titles

      # Memory optimization settings
       WARRACKER_MEMORY_MODE: ${WARRACKER_MEMORY_MODE} # Options: optimized (default), ultra-light

    restart: always
networks:
  innendienst:
    external: true

```
Seems like Warracker still wants admin :(

**Comment by sassanix** [comment]
Hi @Morethanevil , looking at your docker compose now.


```
networks:
  innendienst:
    external: true
```

Ensure:

- The external PostgreSQL server is accessible from this Docker network.
- If it's another container, it must be attached to the same innendienst network.
- If it's a host-level service, its IP (like 172.20.0.10) must be reachable from inside the container.

Assuming your external postgresql is at 172.20.0.10 try this working example for the docker compose:


```
services:
  warracker:
    image: ghcr.io/sassanix/warracker/main:latest
    container_name: warracker
    ports:
      - "8005:80"
    networks:
      innendienst:
        ipv4_address: 172.20.0.71
        ipv6_address: fd00:112::71
    volumes:
      - /docker/warracker/uploads:/data/uploads
    environment:
      DB_HOST: 172.20.0.10
      DB_NAME: warranty_db
      DB_USER: warranty_user
      DB_PASSWORD: your_password
      SMTP_HOST: smtp.email.com
      SMTP_PORT: 465
      SMTP_USERNAME: youremail@email.com
      SMTP_PASSWORD: password
      SECRET_KEY: your_strong_secret_key
      MAX_UPLOAD_MB: 50
      NGINX_MAX_BODY_SIZE_VALUE: 50M
      OIDC_PROVIDER_NAME: Authentik
      OIDC_CLIENT_ID: your_oidc_client_id
      OIDC_CLIENT_SECRET: your_oidc_client_secret
      OIDC_ISSUER_URL: https://your-oidc-provider.com/realm
      OIDC_SCOPE: openid email profile
      FRONTEND_URL: http://your.domain.com
      APP_BASE_URL: http://your.domain.com
      APPRISE_ENABLED: true
      APPRISE_URLS: your_apprise_urls
      APPRISE_EXPIRATION_DAYS: 30
      APPRISE_NOTIFICATION_TIME: 14:00
      APPRISE_TITLE_PREFIX: Warracker
      WARRACKER_MEMORY_MODE: optimized
    restart: always

networks:
  innendienst:
    external: true
```

**Comment by sassanix** [comment]
I just released a new update to address these issues, please update to the latest version. If you come across any issues, let me know :)

**Comment by Morethanevil** [comment]
The postgres on the host is reachable (- __main__ - INFO - Database connection successful-), the first migrations are done without issues. Warracker still tries admin actions like CREATE ROLE, which is not allowed, since the database user has only normal privileges. The creation of the new user still fails.

I see UID 0 for the container. Would it be possible to change that?

I pulled the new image, nuked the db and recreated it. Here is the docker log output:

```bash
 ✔ Container warracker  Recreated                                                                                  0.1s
Attaching to warracker
warracker  | 2025-06-16 11:32:54,295 INFO Set uid to user 0 succeeded
warracker  | 2025-06-16 11:32:54,295 INFO Set uid to user 0 succeeded
warracker  | 2025-06-16 11:32:54,298 INFO supervisord started with pid 1
warracker  | 2025-06-16 11:32:54,298 INFO supervisord started with pid 1
warracker  | 2025-06-16 11:32:55,303 INFO spawned: 'setup' with pid 7
warracker  | 2025-06-16 11:32:55,303 INFO spawned: 'setup' with pid 7
warracker  | 2025-06-16 11:32:55,311 INFO spawned: 'nginx' with pid 8
warracker  | 2025-06-16 11:32:55,311 INFO spawned: 'nginx' with pid 8
warracker  | 2025-06-16 11:32:55,316 INFO spawned: 'gunicorn' with pid 10
warracker  | 2025-06-16 11:32:55,316 INFO spawned: 'gunicorn' with pid 10
warracker  | Running database migrations...
warracker  | 2025-06-16 11:32:55,317 INFO success: setup entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
warracker  | 2025-06-16 11:32:55,317 INFO success: setup entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
warracker  | --- Start of Processed Nginx default.conf ---
warracker  | server {
warracker  |     listen 80;
warracker  |     listen [::]:80;
warracker  |     server_name localhost;
warracker  |     # Point root to the frontend directory where static assets reside inside the container
warracker  |     root /var/www/html;
warracker  |     index index.html;
warracker  |
warracker  |     # Enable detailed error logging
warracker  |     error_log /var/log/nginx/error.log debug;
warracker  |     access_log /var/log/nginx/access.log;
warracker  |
warracker  |     # Global settings
warracker  |     gzip on;
warracker  |     gzip_types text/plain text/css application/javascript application/json;
warracker  |     client_max_body_size 50M; # Configurable global limit
warracker  |
warracker  |     # Add CORS headers globally
warracker  |     add_header 'Access-Control-Allow-Origin' '*';
warracker  |     add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE';
warracker  |     add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
warracker  |
warracker  |     # MIME types - fixed duplicate js entry
warracker  |     types {
warracker  |         text/html                             html htm shtml;
warracker  |         text/css                              css;
warracker  |         application/javascript                js;
warracker  |         image/png                             png;
warracker  |         image/jpeg                            jpg jpeg;
warracker  |         image/gif                             gif;
warracker  |         image/svg+xml                         svg svgz;
warracker  |         application/pdf                       pdf;
warracker  |         image/x-icon                          ico;
warracker  |         application/json                      json;
warracker  |         application/manifest+json             webmanifest manifest;
warracker  |     }
warracker  |
warracker  |     # API requests - proxy to backend (fixed upstream host)
warracker  |     # Using ^~ to ensure this prefix match takes precedence over regex extension matches
warracker  |     location ^~ /api/ {
warracker  |         proxy_pass http://127.0.0.1:5000; # Removed trailing slash to pass /api/ prefix
warracker  |         proxy_set_header Host $host;
warracker  |         proxy_set_header X-Real-IP $remote_addr;
warracker  |         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
warracker  |         proxy_set_header X-Forwarded-Proto $scheme;
warracker  |         client_max_body_size 50M; # Configurable limit for API location
warracker  |
warracker  |         # Pass Authorization header to backend
warracker  |         proxy_set_header Authorization $http_authorization;
warracker  |
warracker  |         # Enhanced proxy settings for file handling
warracker  |         proxy_buffering off; # Disable buffering for file downloads to prevent content-length mismatches
warracker  |         proxy_request_buffering off; # Disable request buffering for uploads
warracker  |         proxy_read_timeout 300s; # Increased timeout for large file transfers
warracker  |         proxy_connect_timeout 30s;
warracker  |         proxy_send_timeout 300s;
warracker  |
warracker  |         # Prevent proxy from modifying response headers that could cause issues
warracker  |         proxy_set_header Connection "";
warracker  |         proxy_http_version 1.1;
warracker  |
warracker  |         # Add debug headers to see what's happening
warracker  |         add_header X-Debug-Message "API request proxied to backend" always;
warracker  |
warracker  |         # CORS for API
warracker  |         add_header 'Access-Control-Allow-Origin' '*' always;
warracker  |         add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
warracker  |         add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
warracker  |
warracker  |         # CORS preflight
warracker  |         if ($request_method = 'OPTIONS') {
warracker  |             add_header 'Access-Control-Allow-Origin' '*' always;
warracker  |             add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
warracker  |             add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
warracker  |             add_header 'Access-Control-Max-Age' 1728000 always;
warracker  |             add_header 'Content-Type' 'text/plain charset=UTF-8' always;
warracker  |             add_header 'Content-Length' 0 always;
warracker  |             return 204;
warracker  |         }
warracker  |     }
warracker  |
warracker  |     # Uploads - serve files from uploads directory
warracker  |     location /uploads/ {
warracker  |         return 403 "Access forbidden";
warracker  |     }
warracker  |
warracker  |     # HTML files - ensure proper content type
warracker  |     location ~ \.html$ {
warracker  |         add_header Content-Type "text/html; charset=utf-8";
warracker  |         add_header Cache-Control "no-cache, no-store, must-revalidate";
warracker  |     }
warracker  |
warracker  |     # Favicon - specific handling
warracker  |     location = /favicon.ico {
warracker  |         log_not_found off;
warracker  |         access_log off;
warracker  |         try_files $uri =404;
warracker  |         expires 7d;
warracker  |         add_header Cache-Control "public, max-age=604800";
warracker  |     }
warracker  |
warracker  |     # Static assets (CSS, JS, images)
warracker  |     location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg)$ {
warracker  |         try_files $uri =404;
warracker  |         expires 7d;
warracker  |         add_header Cache-Control "public, max-age=604800";
warracker  |     }
warracker  |
warracker  |     # Test uploads path
warracker  |     location = /test-uploads {
warracker  |         add_header Content-Type text/plain;
warracker  |         return 200 "Uploads directory exists: $document_root\n";
warracker  |     }
warracker  |
warracker  |     # Specific handling for manifest.json
warracker  |     location = /manifest.json {
warracker  |         alias /var/www/html/manifest.json; # Serve from this specific path
warracker  |         # The global types block should set the correct Content-Type
warracker  |         # (application/manifest+json for 'manifest' extension)
warracker  |         # If not found by alias, it will result in a 404, which is correct.
warracker  |         # No need for try_files here if alias is used and file must exist.
warracker  |         # If you want to be explicit about 404 if alias target doesn't exist:
warracker  |         # if (!-f /var/www/html/manifest.json) { return 404; }
warracker  |         # However, alias itself should handle this.
warracker  |         # Add caching headers if desired, e.g.:
warracker  |         # expires 1d;
warracker  |         # add_header Cache-Control "public, must-revalidate";
warracker  |     }
warracker  |
warracker  |     # Default location
warracker  |     location / {
warracker  |         try_files $uri $uri/ /index.html;
warracker  |     }
warracker  | }
warracker  | --- End of Processed Nginx default.conf ---
warracker  | 2025-06-16 11:32:55,463 - __main__ - INFO - Attempting to connect to database (attempt 1/5)
warracker  | 2025-06-16 11:32:55,477 - __main__ - INFO - Database connection successful
warracker  | 2025-06-16 11:32:55,488 - __main__ - INFO - Applying migration: 000_create_warranties_table.sql
warracker  | 2025-06-16 11:32:55,495 - __main__ - INFO - Migration 000_create_warranties_table.sql applied successfully
warracker  | 2025-06-16 11:32:55,495 - __main__ - INFO - Applying migration: 001_add_serial_numbers.sql
warracker  | 2025-06-16 11:32:55,506 - __main__ - INFO - Migration 001_add_serial_numbers.sql applied successfully
warracker  | 2025-06-16 11:32:55,506 - __main__ - INFO - Applying migration: 002_add_purchase_price.sql
warracker  | 2025-06-16 11:32:55,517 - __main__ - INFO - Migration 002_add_purchase_price.sql applied successfully
warracker  | 2025-06-16 11:32:55,517 - __main__ - INFO - Applying migration: 003_add_users_table.sql
warracker  | 2025-06-16 11:32:55,537 - __main__ - INFO - Migration 003_add_users_table.sql applied successfully
warracker  | 2025-06-16 11:32:55,538 - __main__ - INFO - Applying migration: 004_create_user_preferences_table.py
warracker  | Created user_preferences table
warracker  | 2025-06-16 11:32:55,547 - __main__ - INFO - Migration 004_create_user_preferences_table.py applied successfully
warracker  | 2025-06-16 11:32:55,548 - __main__ - INFO - Applying migration: 005_add_expiring_soon_days_column.py
warracker  | Added expiring_soon_days column to existing user_preferences table
warracker  | 2025-06-16 11:32:55,553 - __main__ - INFO - Migration 005_add_expiring_soon_days_column.py applied successfully
warracker  | 2025-06-16 11:32:55,553 - __main__ - INFO - Applying migration: 006_add_currency_symbol_column.py
warracker  | Added currency_symbol column to user_preferences table
warracker  | 2025-06-16 11:32:55,560 - __main__ - INFO - Migration 006_add_currency_symbol_column.py applied successfully
warracker  | 2025-06-16 11:32:55,560 - __main__ - INFO - Applying migration: 007_add_notification_preferences.sql
warracker  | 2025-06-16 11:32:55,570 - __main__ - INFO - Migration 007_add_notification_preferences.sql applied successfully
warracker  | 2025-06-16 11:32:55,570 - __main__ - INFO - Applying migration: 008_add_tags.sql
warracker  | 2025-06-16 11:32:55,581 - __main__ - INFO - Migration 008_add_tags.sql applied successfully
warracker  | 2025-06-16 11:32:55,581 - __main__ - INFO - Applying migration: 009_add_admin_flag_to_tags.sql
warracker  | 2025-06-16 11:32:55,584 - __main__ - INFO - Migration 009_add_admin_flag_to_tags.sql applied successfully
warracker  | 2025-06-16 11:32:55,585 - __main__ - INFO - Applying migration: 010_configure_admin_roles.sql
warracker  | 2025-06-16 11:32:55,587 - __main__ - ERROR - Error applying migration 010_configure_admin_roles.sql: FEHLER:  keine Berechtigung, um Rolle zu erzeugen
warracker  | DETAIL:  Nur Rollen mit dem CREATEROLE-Attribut können Rollen erzeugen.
warracker  | CONTEXT:  SQL-Anweisung »CREATE ROLE warracker_admin WITH LOGIN PASSWORD 'change_this_password_in_production'«
warracker  | PL/pgSQL-Funktion inline_code_block Zeile 5 bei SQL-Anweisung
warracker  |
warracker  | 2025-06-16 11:32:55,587 - __main__ - ERROR -
warracker  | QUERY: -- Migration: Configure PostgreSQL Admin Role
warracker  |
warracker  | -- Create a new database role for admin operations
warracker  | DO $$
warracker  | BEGIN
warracker  |     -- Check if the db_admin_user exists, if not create it
warracker  |     IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '%(db_admin_user)s') THEN
warracker  |         CREATE ROLE %(db_admin_user)s WITH LOGIN PASSWORD '%(db_admin_password)s';
warracker  |     END IF;
warracker  | END
warracker  | $$;
warracker  |
warracker  | -- Grant privileges to the admin role
warracker  | GRANT ALL PRIVILEGES ON DATABASE %(db_name)s TO %(db_admin_user)s;
warracker  | GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO %(db_admin_user)s;
warracker  | GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO %(db_admin_user)s;
warracker  | GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO %(db_admin_user)s;
warracker  |
warracker  | -- Grant specific role management permissions
warracker  | ALTER ROLE %(db_admin_user)s WITH CREATEROLE;
warracker  |
warracker  | -- Ensure the db_user can still access all application tables
warracker  | GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO %(db_user)s;
warracker  | GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO %(db_user)s;
warracker  | GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO %(db_user)s;
warracker  |
warracker  | -- Make db_admin_user the owner of all existing users
warracker  | -- Note: This would require superuser privileges to execute
warracker  | -- ALTER ROLE %(db_user)s OWNER TO %(db_admin_user)s;
warracker  |
warracker  |
warracker  | 2025-06-16 11:32:55,587 - __main__ - ERROR - Migration error: FEHLER:  keine Berechtigung, um Rolle zu erzeugen
warracker  | DETAIL:  Nur Rollen mit dem CREATEROLE-Attribut können Rollen erzeugen.
warracker  | CONTEXT:  SQL-Anweisung »CREATE ROLE warracker_admin WITH LOGIN PASSWORD 'change_this_password_in_production'«
warracker  | PL/pgSQL-Funktion inline_code_block Zeile 5 bei SQL-Anweisung
warracker  |
warracker  | 2025-06-16 11:32:55,587 - __main__ - ERROR - Migration process failed: FEHLER:  keine Berechtigung, um Rolle zu erzeugen
warracker  | DETAIL:  Nur Rollen mit dem CREATEROLE-Attribut können Rollen erzeugen.
warracker  | CONTEXT:  SQL-Anweisung »CREATE ROLE warracker_admin WITH LOGIN PASSWORD 'change_this_password_in_production'«
warracker  | PL/pgSQL-Funktion inline_code_block Zeile 5 bei SQL-Anweisung
warracker  |
warracker  | 2025-06-16 11:32:55,611 WARN exited: setup (exit status 1; not expected)
warracker  | 2025-06-16 11:32:55,611 WARN exited: setup (exit status 1; not expected)
warracker  | ✅ Early gevent monkey patch applied for SSL compatibility.
warracker  | Using PERFORMANCE memory mode - maximum concurrency and performance
warracker  | ℹ️ Using gevent workers with early monkey patching applied.
warracker  | Gunicorn configuration loaded: 4 gevent workers in PERFORMANCE mode
warracker  | Memory limit per worker: 256MB, Max connections: 200
warracker  | ✅ Apprise successfully imported
warracker  | ✅ Database functions imported from backend.db_handler
warracker  | ERROR:backend.db_handler:[DB_HANDLER] Database connection pool is None. Attempting to re-initialize.
warracker  | INFO:backend.db_handler:[DB_HANDLER] Attempting to initialize database pool (attempt 1/5)
warracker  | INFO:backend.db_handler:[DB_HANDLER] Database connection pool initialized successfully.
warracker  | ERROR:backend.db_handler:Error getting site setting apprise_enabled: FEHLER:  Relation »site_settings« existiert nicht
warracker  | LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_enabled...
warracker  |                           ^
warracker  |
warracker  | ERROR:backend.db_handler:Error getting site setting apprise_urls: FEHLER:  Relation »site_settings« existiert nicht
warracker  | LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_urls'
warracker  |                           ^
warracker  |
warracker  | ERROR:backend.db_handler:Error getting site setting apprise_expiration_days: FEHLER:  Relation »site_settings« existiert nicht
warracker  | LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_expirat...
warracker  |                           ^
warracker  |
warracker  | ERROR:backend.db_handler:Error getting site setting apprise_notification_time: FEHLER:  Relation »site_settings« existiert nicht
warracker  | LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_notific...
warracker  |                           ^
warracker  |
warracker  | ERROR:backend.db_handler:Error getting site setting apprise_title_prefix: FEHLER:  Relation »site_settings« existiert nicht
warracker  | LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_title_p...
warracker  |                           ^
warracker  |
warracker  | INFO:backend.apprise_handler:Successfully added Apprise URL: gotifys://gfy.storag...
warracker  | INFO:backend.apprise_handler:Apprise configuration loaded: enabled=True, urls_count=1
warracker  | INFO:backend.apprise_handler:Apprise notification handler initialized successfully
warracker  | ERROR:backend.db_handler:Error getting site setting apprise_enabled: FEHLER:  Relation »site_settings« existiert nicht
warracker  | LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_enabled...
warracker  |                           ^
warracker  |
warracker  | ERROR:backend.db_handler:Error getting site setting apprise_urls: FEHLER:  Relation »site_settings« existiert nicht
warracker  | LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_urls'
warracker  |                           ^
warracker  |
warracker  | ERROR:backend.db_handler:Error getting site setting apprise_expiration_days: FEHLER:  Relation »site_settings« existiert nicht
warracker  | LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_expirat...
warracker  |                           ^
warracker  |
warracker  | ERROR:backend.db_handler:Error getting site setting apprise_notification_time: FEHLER:  Relation »site_settings« existiert nicht
warracker  | LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_notific...
warracker  |                           ^
warracker  |
warracker  | ERROR:backend.db_handler:Error getting site setting apprise_title_prefix: FEHLER:  Relation »site_settings« existiert nicht
warracker  | LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_title_p...
warracker  |                           ^
warracker  |
warracker  | INFO:backend.apprise_handler:Successfully added Apprise URL: gotifys://gfy.storag...
warracker  | INFO:backend.apprise_handler:Apprise configuration loaded: enabled=True, urls_count=1
warracker  | INFO:backend.apprise_handler:Apprise notification handler initialized successfully
warracker  | INFO:app:Apprise notification handler imported successfully
warracker  | INFO:backend.db_handler:[DB_HANDLER] Database connection pool already initialized.
warracker  | INFO:app:Database connection pool initialized successfully.
warracker  | INFO:app:Max upload file size set to: 50MB (52428800 bytes)
warracker  | INFO:app:[APP.PY OIDC_INIT] Attempting to initialize OIDC client...
warracker  | ERROR:app:[APP.PY OIDC_INIT] Error fetching OIDC settings from DB: FEHLER:  Relation »site_settings« existiert nicht
warracker  | LINE 1: SELECT key, value FROM site_settings WHERE key LIKE 'oidc_%%...
warracker  |                                ^
warracker  | . Proceeding without DB settings.
warracker  | INFO:app:[APP.PY OIDC_INIT] OIDC enabled status: False
warracker  | INFO:app:[APP.PY OIDC_INIT] OIDC is disabled.
warracker  | INFO:backend.notifications:Scheduler will run in Gunicorn worker (ID: 0, Name: )
warracker  | INFO:backend.notifications:Using BackgroundScheduler with  worker
warracker  | INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly scheduled when the scheduler starts
warracker  | INFO:apscheduler.scheduler:Added job "init_scheduler.<locals>.notification_wrapper" to job store "default"
warracker  | INFO:apscheduler.scheduler:Scheduler started
warracker  | INFO:backend.notifications:✅ Email notification scheduler started - checking every 2 minutes
warracker  | INFO:app:Ensuring application owner exists on startup...
warracker  | INFO:app:is_owner column not yet created, skipping owner check (migrations may still be running)
warracker  | Server is starting with memory-optimized configuration
warracker  | [2025-06-16 11:32:56 +0000] [10] [INFO] Starting gunicorn 23.0.0
warracker  | [2025-06-16 11:32:56 +0000] [10] [INFO] Listening at: http://0.0.0.0:5000 (10)
warracker  | [2025-06-16 11:32:56 +0000] [10] [INFO] Using worker: gevent
warracker  | Forking worker #1
warracker  | [2025-06-16 11:32:56 +0000] [37] [INFO] Booting worker with pid: 37
warracker  | Worker 37 (ID: 0) forked with memory optimization
warracker  | Traceback (most recent call last):
warracker  |   File "src/gevent/_abstract_linkable.py", line 287, in gevent._gevent_c_abstract_linkable.AbstractLinkable._notify_links
warracker  |   File "src/gevent/_abstract_linkable.py", line 333, in gevent._gevent_c_abstract_linkable.AbstractLinkable._notify_links
warracker  | AssertionError: (None, <callback at 0xf9eddc4d6e80 args=([],)>)
warracker  | 2025-06-16T11:32:56Z <callback at 0xf9eddc4d6e80 args=([],)> failed with AssertionError
warracker  |
warracker  | Forking worker #2
warracker  | Worker 38 (ID: 1) forked with memory optimization
warracker  | [2025-06-16 11:32:56 +0000] [38] [INFO] Booting worker with pid: 38
warracker  | Forking worker #3
warracker  | Worker 39 (ID: 2) forked with memory optimization
warracker  | [2025-06-16 11:32:56 +0000] [39] [INFO] Booting worker with pid: 39
warracker  | Forking worker #4
warracker  | [2025-06-16 11:32:57 +0000] [40] [INFO] Booting worker with pid: 40
warracker  | Worker 40 (ID: 3) forked with memory optimization
warracker  | 2025-06-16 11:33:01,080 INFO success: nginx entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
warracker  | 2025-06-16 11:33:01,080 INFO success: nginx entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
warracker  | 2025-06-16 11:33:01,080 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
warracker  | 2025-06-16 11:33:01,080 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
warracker  | ERROR:backend.oidc_handler:[OIDC_HANDLER] Error fetching OIDC status: FEHLER:  Relation »site_settings« existiert nicht
warracker  | LINE 1: SELECT key, value FROM site_settings WHERE key IN ('oidc_ena...
warracker  |                                ^
warracker  |
warracker  | ERROR:app:Error checking registration status: FEHLER:  aktuelle Transaktion wurde abgebrochen, Befehle werden bis zum Ende der Transaktion ignoriert
warracker  |
warracker  | ERROR:app:Registration error: FEHLER:  Spalte »is_owner« von Relation »users« existiert nicht
warracker  | LINE 1: ..., password_hash, first_name, last_name, is_admin, is_owner) ...
warracker  |                                                              ^
warracker  |
warracker  | INFO:apscheduler.executors.default:Running job "init_scheduler.<locals>.notification_wrapper (trigger: interval[0:02:00], next run at: 2025-06-16 11:34:56 UTC)" (scheduled at 2025-06-16 11:34:56.817873+00:00)
warracker  | INFO:backend.notifications:Starting expiration notification process
warracker  | INFO:apscheduler.executors.default:Running job "init_scheduler.<locals>.notification_wrapper (trigger: interval[0:02:00], next run at: 2025-06-16 11:34:56 UTC)" (scheduled at 2025-06-16 11:34:56.817873+00:00)
warracker  | INFO:apscheduler.executors.default:Running job "init_scheduler.<locals>.notification_wrapper (trigger: interval[0:02:00], next run at: 2025-06-16 11:34:56 UTC)" (scheduled at 2025-06-16 11:34:56.817873+00:00)
warracker  | INFO:backend.notifications:Starting expiration notification process
warracker  | INFO:backend.notifications:Starting expiration notification process
warracker  | INFO:apscheduler.executors.default:Running job "init_scheduler.<locals>.notification_wrapper (trigger: interval[0:02:00], next run at: 2025-06-16 11:34:56 UTC)" (scheduled at 2025-06-16 11:34:56.817873+00:00)
warracker  | INFO:backend.notifications:Starting expiration notification process
warracker  | WARNING:backend.notifications:Database connection attempt 1 failed: no results to fetch
warracker  | WARNING:backend.notifications:Database connection attempt 1 failed: no results to fetch
warracker  | INFO:backend.notifications:Retrying database connection in 2 seconds...
warracker  | WARNING:backend.notifications:Database connection attempt 1 failed: error with status PGRES_TUPLES_OK and no message from the libpq
warracker  | INFO:backend.notifications:Retrying database connection in 2 seconds...
warracker  | INFO:apscheduler.executors.default:Running job "init_scheduler.<locals>.notification_wrapper (trigger: interval[0:02:00], next run at: 2025-06-16 11:34:56 UTC)" (scheduled at 2025-06-16 11:34:56.817873+00:00)
warracker  | INFO:backend.notifications:Starting expiration notification process
warracker  | INFO:backend.notifications:Retrying database connection in 2 seconds...
warracker  | WARNING:backend.notifications:Database connection attempt 2 failed: error with status PGRES_TUPLES_OK and no message from the libpq
warracker  | WARNING:backend.notifications:Database connection attempt 2 failed: no results to fetch
warracker  | INFO:backend.notifications:Retrying database connection in 2 seconds...
warracker  | INFO:backend.notifications:Retrying database connection in 2 seconds...
warracker  | WARNING:backend.notifications:Database connection attempt 2 failed: error with status PGRES_TUPLES_OK and no message from the libpq
warracker  | INFO:backend.notifications:Retrying database connection in 2 seconds...
warracker  | WARNING:backend.notifications:Database connection attempt 3 failed: no results to fetch
warracker  | WARNING:backend.notifications:Database connection attempt 3 failed: error with status PGRES_TUPLES_OK and no message from the libpq
warracker  | ERROR:backend.notifications:All database connection attempts failed
warracker  | ERROR:backend.notifications:All database connection attempts failed
warracker  | INFO:apscheduler.executors.default:Job "init_scheduler.<locals>.notification_wrapper (trigger: interval[0:02:00], next run at: 2025-06-16 11:36:56 UTC)" executed successfully
warracker  | INFO:apscheduler.executors.default:Job "init_scheduler.<locals>.notification_wrapper (trigger: interval[0:02:00], next run at: 2025-06-16 11:36:56 UTC)" executed successfully
warracker  | ERROR:backend.notifications:Error determining notification eligibility: FEHLER:  Spalte up.timezone existiert nicht
warracker  | LINE 2: ....id, u.email, u.first_name, up.notification_time, up.timezon...
warracker  |                                                              ^
warracker  |
warracker  | INFO:apscheduler.executors.default:Job "init_scheduler.<locals>.notification_wrapper (trigger: interval[0:02:00], next run at: 2025-06-16 11:34:56 UTC)" executed successfully
```

**Comment by sassanix** [comment]
Thank you for sharing all the logs, I will work on a fix for the next update soon. Thanks again for your patience!

**Comment by Morethanevil** [comment]
> [@Morethanevil](https://github.com/Morethanevil) Please update to the latest version, and let me know if it works for you now.

Nope, it still tries to create a user. I dropped the database and created a fresh one.

Docker logs:

```bash
--- End of Processed Nginx default.conf ---
2025-06-25 15:29:07,859 - __main__ - INFO - Attempting to connect to database (attempt 1/5)
2025-06-25 15:29:07,873 - __main__ - INFO - Database connection successful
2025-06-25 15:29:07,886 - __main__ - INFO - Applying migration: 000_create_warranties_table.sql
2025-06-25 15:29:07,905 - __main__ - INFO - Migration 000_create_warranties_table.sql applied successfully
2025-06-25 15:29:07,905 - __main__ - INFO - Applying migration: 001_add_serial_numbers.sql
2025-06-25 15:29:07,920 - __main__ - INFO - Migration 001_add_serial_numbers.sql applied successfully
2025-06-25 15:29:07,920 - __main__ - INFO - Applying migration: 002_add_purchase_price.sql
2025-06-25 15:29:07,932 - __main__ - INFO - Migration 002_add_purchase_price.sql applied successfully
2025-06-25 15:29:07,933 - __main__ - INFO - Applying migration: 003_add_users_table.sql
2025-06-25 15:29:07,963 - __main__ - INFO - Migration 003_add_users_table.sql applied successfully
2025-06-25 15:29:07,963 - __main__ - INFO - Applying migration: 004_create_user_preferences_table.py
Created user_preferences table
2025-06-25 15:29:07,976 - __main__ - INFO - Migration 004_create_user_preferences_table.py applied successfully
2025-06-25 15:29:07,976 - __main__ - INFO - Applying migration: 005_add_expiring_soon_days_column.py
Added expiring_soon_days column to existing user_preferences table
2025-06-25 15:29:07,983 - __main__ - INFO - Migration 005_add_expiring_soon_days_column.py applied successfully
2025-06-25 15:29:07,983 - __main__ - INFO - Applying migration: 006_add_currency_symbol_column.py
Added currency_symbol column to user_preferences table
2025-06-25 15:29:07,991 - __main__ - INFO - Migration 006_add_currency_symbol_column.py applied successfully
2025-06-25 15:29:07,991 - __main__ - INFO - Applying migration: 007_add_notification_preferences.sql
2025-06-25 15:29:08,003 - __main__ - INFO - Migration 007_add_notification_preferences.sql applied successfully
2025-06-25 15:29:08,003 - __main__ - INFO - Applying migration: 008_add_tags.sql
2025-06-25 15:29:08,015 - __main__ - INFO - Migration 008_add_tags.sql applied successfully
2025-06-25 15:29:08,015 - __main__ - INFO - Applying migration: 009_add_admin_flag_to_tags.sql
2025-06-25 15:29:08,019 - __main__ - INFO - Migration 009_add_admin_flag_to_tags.sql applied successfully
2025-06-25 15:29:08,019 - __main__ - INFO - Applying migration: 010_configure_admin_roles.sql
2025-06-25 15:29:08,023 - __main__ - ERROR - Error applying migration 010_configure_admin_roles.sql: FEHLER:  keine Berechtigung, um Rolle zu erzeugen
DETAIL:  Nur Rollen mit dem CREATEROLE-Attribut können Rollen erzeugen.
CONTEXT:  SQL-Anweisung »CREATE ROLE warracker_admin WITH LOGIN PASSWORD
'change_this_password_in_production'«
PL/pgSQL-Funktion inline_code_block Zeile 5 bei SQL-Anweisung
2025-06-25 15:29:08,023 - __main__ - ERROR -
QUERY: -- Migration: Configure PostgreSQL Admin Role
-- Create a new database role for admin operations
DO $$
BEGIN
    -- Check if the db_admin_user exists, if not create it
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '%(db_admin_user)s') THEN
        CREATE ROLE %(db_admin_user)s WITH LOGIN PASSWORD '%(db_admin_password)s';
    END IF;
END
$$;
-- Grant privileges to the admin role
GRANT ALL PRIVILEGES ON DATABASE %(db_name)s TO %(db_admin_user)s;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO %(db_admin_user)s;GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO %(db_admin_user)s;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO %(db_admin_user)s;
-- Grant specific role management permissions
ALTER ROLE %(db_admin_user)s WITH CREATEROLE;
-- Ensure the db_user can still access all application tables
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO %(db_user)s;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO %(db_user)s;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO %(db_user)s;
-- Make db_admin_user the owner of all existing users
-- Note: This would require superuser privileges to execute
-- ALTER ROLE %(db_user)s OWNER TO %(db_admin_user)s;
2025-06-25 15:29:08,023 - __main__ - ERROR - Migration error: FEHLER:  keine Berechtigung, um Rolle zu erzeugen
DETAIL:  Nur Rollen mit dem CREATEROLE-Attribut können Rollen erzeugen.
CONTEXT:  SQL-Anweisung »CREATE ROLE warracker_admin WITH LOGIN PASSWORD
'change_this_password_in_production'«
PL/pgSQL-Funktion inline_code_block Zeile 5 bei SQL-Anweisung
2025-06-25 15:29:08,024 - __main__ - ERROR - Migration process failed: FEHLER:  keine Berechtigung, um Rolle zu erzeugen
DETAIL:  Nur Rollen mit dem CREATEROLE-Attribut können Rollen erzeugen.
CONTEXT:  SQL-Anweisung »CREATE ROLE warracker_admin WITH LOGIN PASSWORD
'change_this_password_in_production'«
PL/pgSQL-Funktion inline_code_block Zeile 5 bei SQL-Anweisung
2025-06-25 15:29:08,055 WARN exited: setup (exit status 1; not expected)
2025-06-25 15:29:08,055 WARN exited: setup (exit status 1; not expected)
✅  Early gevent monkey patch applied for SSL compatibility.
Using PERFORMANCE memory mode - maximum concurrency and performance
ℹ️ Using gevent workers with early monkey patching applied.
Gunicorn configuration loaded: 4 gevent workers in PERFORMANCE mode
Memory limit per worker: 256MB, Max connections: 200
ERROR:backend.db_handler:[DB_HANDLER] Database connection pool is None. Attempting to re-initialize.
INFO:backend.db_handler:[DB_HANDLER] Attempting to initialize database pool (attempt 1/5)
✅  Apprise successfully imported
✅  Database functions imported from backend.db_handler
INFO:backend.db_handler:[DB_HANDLER] Database connection pool initialized successfully.
ERROR:backend.db_handler:Error getting site setting apprise_enabled: FEHLER:  Relation »site_settings« existiert nicht
LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_enabled...
                          ^
ERROR:backend.db_handler:Error getting site setting apprise_urls: FEHLER:  Relation »site_settings« existiert nicht
LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_urls'
                          ^
ERROR:backend.db_handler:Error getting site setting apprise_expiration_days: FEHLER:  Relation »site_settings« existiert nicht
LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_expirat...
                          ^
ERROR:backend.db_handler:Error getting site setting apprise_notification_time: FEHLER:  Relation »site_settings« existiert nicht
LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_notific...
                          ^
ERROR:backend.db_handler:Error getting site setting apprise_title_prefix: FEHLER:  Relation »site_settings« existiert nicht
LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_title_p...
                          ^
INFO:backend.apprise_handler:Successfully added Apprise URL: gotifys://gfy.storag...
INFO:backend.apprise_handler:Apprise configuration loaded: enabled=True,
urls_count=1
INFO:backend.apprise_handler:Apprise notification handler initialized successfully
ERROR:backend.db_handler:Error getting site setting apprise_enabled: FEHLER:  Relation »site_settings« existiert nicht
LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_enabled...
                          ^
ERROR:backend.db_handler:Error getting site setting apprise_urls: FEHLER:  Relation »site_settings« existiert nicht
LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_urls'
                          ^
ERROR:backend.db_handler:Error getting site setting apprise_expiration_days: FEHLER:  Relation »site_settings« existiert nicht
LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_expirat...
                          ^
ERROR:backend.db_handler:Error getting site setting apprise_notification_time: FEHLER:  Relation »site_settings« existiert nicht
LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_notific...
                          ^
ERROR:backend.db_handler:Error getting site setting apprise_title_prefix: FEHLER:  Relation »site_settings« existiert nicht
LINE 1: SELECT value FROM site_settings WHERE key = 'apprise_title_p...
                          ^
INFO:backend.apprise_handler:Successfully added Apprise URL: gotifys://gfy.storag...
INFO:backend.apprise_handler:Apprise configuration loaded: enabled=True,
urls_count=1
INFO:backend.apprise_handler:Apprise notification handler initialized successfully
INFO:app:Apprise notification handler imported successfully
INFO:backend.db_handler:[DB_HANDLER] Database connection pool already initialized.
INFO:app:Database connection pool initialized successfully.
INFO:app:Max upload file size set to: 50MB (52428800 bytes)
INFO:app:[APP.PY OIDC_INIT] Attempting to initialize OIDC client...
ERROR:app:[APP.PY OIDC_INIT] Error fetching OIDC settings from DB: FEHLER:  Relation »site_settings« existiert nicht
LINE 1: SELECT key, value FROM site_settings WHERE key LIKE 'oidc_%%...
                               ^
. Proceeding without DB settings.
INFO:app:[APP.PY OIDC_INIT] OIDC enabled status: False
INFO:app:[APP.PY OIDC_INIT] OIDC is disabled.
INFO:backend.notifications:Scheduler will run in Gunicorn worker (ID: 0,
Name: )
INFO:backend.notifications:Using BackgroundScheduler with  worker
INFO:apscheduler.scheduler:Adding job tentatively -- it will be properly
scheduled when the scheduler starts
INFO:apscheduler.scheduler:Added job "init_scheduler.<locals>.notification_wrapper" to job store "default"
INFO:apscheduler.scheduler:Scheduler started
INFO:backend.notifications:✅  Email notification scheduler started - checking every 2 minutes
INFO:app:Ensuring application owner exists on startup...
INFO:app:is_owner column not yet created, skipping owner check (migrations may still be running)
Server is starting with memory-optimized configuration
Forking worker #1
[2025-06-25 15:29:09 +0000] [9] [INFO] Starting gunicorn 23.0.0
[2025-06-25 15:29:09 +0000] [9] [INFO] Listening at: http://0.0.0.0:5000
(9)
[2025-06-25 15:29:09 +0000] [9] [INFO] Using worker: gevent
Worker 37 (ID: 0) forked with memory optimization
[2025-06-25 15:29:09 +0000] [37] [INFO] Booting worker with pid: 37
Traceback (most recent call last):
  File "src/gevent/_abstract_linkable.py", line 287, in gevent._gevent_c_abstract_linkable.AbstractLinkable._notify_links
  File "src/gevent/_abstract_linkable.py", line 333, in gevent._gevent_c_abstract_linkable.AbstractLinkable._notify_links
AssertionError: (None, <callback at 0xf2a4a97e3080 args=([],)>)
2025-06-25T15:29:09Z <callback at 0xf2a4a97e3080 args=([],)> failed with
AssertionError
Forking worker #2
[2025-06-25 15:29:09 +0000] [38] [INFO] Booting worker with pid: 38
Worker 38 (ID: 1) forked with memory optimization
Forking worker #3
[2025-06-25 15:29:09 +0000] [39] [INFO] Booting worker with pid: 39
Worker 39 (ID: 2) forked with memory optimization
Forking worker #4
[2025-06-25 15:29:09 +0000] [40] [INFO] Booting worker with pid: 40
Worker 40 (ID: 3) forked with memory optimization
2025-06-25 15:29:13,497 INFO success: nginx entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2025-06-25 15:29:13,497 INFO success: nginx entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2025-06-25 15:29:13,497 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2025-06-25 15:29:13,497 INFO success: gunicorn entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
```

**Comment by Morethanevil** [comment]
> I will review everything you've shared, thanks again for your feedback :)
> 
> I will let you know if I have more questions.

Thanks for your effort 👍🏻

**Comment by sassanix** [comment]
> I was experiencing the same issue and was able to resolve this by SSHing into the container and running the below commands.
> 
> ```
> rm -fv migrations/011_ensure_admin_permissions.sql migrations/010_configure_admin_roles.sql
> python migrations/apply_migrations.py
> ```
> 
> I believe the 010 and 011 migrations should not be there at all. The things they do should are atypical in an app migration and should be unnecessary as long as the migrations are initially being run with a user with limited permissions to the database.
> 
> [@sassanix](https://github.com/sassanix) [@Morethanevil](https://github.com/Morethanevil)

That is ideal, if you don't want to have more than one user. And the apply migrations, I have it for the docker-compose. I will review that again, and make sure I can set up the migrations, without losing the multi user capabilities.

**Comment by Morethanevil** [comment]
Tried again today with the newest release, still the same. Mark me if this got fixed. Errors are the same as mentioned above :)

**Comment by sassanix** [comment]
> Tried again today with the newest release, still the same. Mark me if this got fixed. Errors are the same as mentioned above :)

Working on a fix, will be a priority for the next release. I'm trying to replicate it, and also once I have a release candidate, I'll send it your way to confirm the fix. 

I appreciate your patience.

**Comment by sassanix** [comment]
This is now fixed in the latest update, please let me know if it still doesn't work for you. Please re-share your docker logs if it happens. 

I will now close this issue, but will re-open if it's not fixed on your end. 

Thanks again for your feedback!

**Comment by sassanix** [comment]
I apologize, I thought it would have fixed your issues. 

I'm trying to figure it out. I'll let you know if I need anything.

**Comment by Morethanevil** [comment]
@sassanix 
Finally, it works without issues :D
Only one thing I found in the logs:

```bash
Migration 040_update_language_constraint.py applied successfully.
2025-07-21 12:58:04,997 - __main__ - INFO - Migration 041_update_language_constraint_again.py applied successfully
2025-07-21 12:58:04,997 - __main__ - INFO - Applying migration: 042_allow_higher_duration_components.sql
2025-07-21 12:58:05,004 - __main__ - INFO - Migration 042_allow_higher_duration_components.sql applied successfully
2025-07-21 12:58:05,004 - __main__ - INFO - Migrations completed successfully
Running fix permissions script...
INFO:backend:Starting application factory...
INFO:backend.config:Max upload file size set to: 50MB
INFO:backend.config:Application configuration initialized successfully
INFO:backend.config:Development configuration loaded
INFO:backend:Configuration 'default' loaded successfully
INFO:__main__:Attempting to connect to database (attempt 1/5)
INFO:__main__:Database connection successful
INFO:__main__:Executing fix permissions SQL script...


ERROR:__main__:Error fixing permissions: FEHLER:  keine Berechtigung, um Rolle zu ändern
DETAIL:  Nur Rollen mit dem CREATEROLE-Attribut und der ADMIN-Option für Rolle »warranty« können diese Rolle ändern.


2025-07-21 12:58:05,177 WARN exited: setup (exit status 1; not expected)
2025-07-21 12:58:05,177 WARN exited: setup (exit status 1; not expected)
INFO:backend.extensions:Initializing Flask extensions...
INFO:backend.extensions:OAuth initialized
INFO:backend.extensions:CORS initialized
INFO:backend.extensions:Bcrypt initialized
INFO:backend.localization:Babel initialized successfully
INFO:backend.extensions:Babel localization initialized successfully
INFO:backend.db_handler:[DB_HANDLER] Attempting to initialize database pool (attempt 1/5)
INFO:backend.db_handler:[DB_HANDLER] Database connection pool initialized successfully.
INFO:backend.extensions:Database connection pool initialized successfully
✅ Apprise successfully imported
✅ Database functions imported from backend.db_handler

```
I can create a user and login. The only thing left as a problem for me is OIDC can not be enabled, mentioned in this [issue here](https://github.com/sassanix/Warracker/issues/107)

Let me say thanks for your hard work on this, I just donated :)

Closing here, since OIDC is tracked in the other issue

**Comment by sassanix** [comment]
@Morethanevil , thank you so much for the support! I will add you to the list. It really means a lot to me, and I appreciate it ❤️

I have been working on the OIDC as well, I will keep everyone updated once I have finalized a proper fix.
